### ISSUE TITLE
mmap can be used for allocating such memory regions for DMA

### ISSUE THREAD

**Issue by ft-** [emmericp/ixy#3]
mmap can be used for allocating such memory regions for DMA.

map(NULL, length, PROT_READ |PROT_WRITE, MAP_ANONYMOUS | MAP_HUGETLB | MAP_LOCKED, 0, 0);

This kind of allocation is done in programs that need specific properties on allocated memory blocks as well (e.g. Wine).

**Comment by emmericp** [comment]
I didn't use that because I thought it was unreliable for some reason. Turns out I was thinking of the madvise huge setting which relies on THP.

Good pointer, thanks!
