### ISSUE TITLE
run ixy-pktgen on virtualbox virtio err: Device does not support required features

### ISSUE THREAD

**Issue by luzhongzhou** [emmericp/ixy#35]
i run virtualbox 6.0 on macos 10.14.6
guest os is ubuntu 16.04. 

guest network device is set **Paravirtualized network adapter (virtio-net)**, as documented in https://www.virtualbox.org/manual/ch06.html

when i run app:
`/home/zzlu/Downloads/uio_test/ixy/cmake-build-debug-remote/ixy-pktgen 0000:00:03.0
[DEBUG] /home/zzlu/Downloads/uio_test/ixy/src/pci.c:58 pci_open_resource(): Opening PCI resource at /sys/bus/pci/devices/0000:00:03.0/config
[DEBUG] /home/zzlu/Downloads/uio_test/ixy/src/pci.c:58 pci_open_resource(): Opening PCI resource at /sys/bus/pci/devices/0000:00:03.0/config
[INFO ] /home/zzlu/Downloads/uio_test/ixy/src/driver/virtio.c:352 virtio_init(): Detected virtio legacy network card
[DEBUG] /home/zzlu/Downloads/uio_test/ixy/src/pci.c:58 pci_open_resource(): Opening PCI resource at /sys/bus/pci/devices/0000:00:03.0/resource0
[DEBUG] /home/zzlu/Downloads/uio_test/ixy/src/driver/virtio.c:275 virtio_legacy_init(): Configuring bar0
[DEBUG] /home/zzlu/Downloads/uio_test/ixy/src/driver/virtio.c:284 virtio_legacy_init(): Host features: 410fdda3
[ERROR] /home/zzlu/Downloads/uio_test/ixy/src/driver/virtio.c:289 virtio_legacy_init(): Device does not support required features`

i can figure out this error in code, my host feature without VIRTIO_F_ANY_LAYOUT
how can i fix this?

**Comment by emmericp** [comment]
You need the branch virtualbox-workarounds, see https://github.com/emmericp/ixy/commit/ea22597d2ea78a8c4cc3cd30305573d381a9303e
